# Generated by Django 5.1.6 on 2025-06-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ethuser',
            name='id',
        ),
        migrations.RemoveField(
            model_name='token',
            name='id',
        ),
        migrations.AddField(
            model_name='ethuser',
            name='nonce',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ethuser',
            name='address',
            field=models.CharField(max_length=42, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
