# Generated by Django 5.1.6 on 2025-06-10 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_remove_ethuser_id_remove_token_id_ethuser_nonce_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
