# Generated by Django 5.1.6 on 2025-06-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_delete_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUrl',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Update_Request',
            fields=[
                ('transaction_hash', models.CharField(editable=False, max_length=88, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(editable=False, max_length=44)),
                ('update_id', models.IntegerField()),
                ('burn_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_name', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=500)),
                ('updated', models.BooleanField(default=False)),
            ],
        ),
    ]
