# Generated by Django 5.1.6 on 2025-06-27 12:18

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_expiringtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update_request',
            old_name='updated',
            new_name='downloaded',
        ),
        migrations.RemoveField(
            model_name='update_request',
            name='burn_id',
        ),
        migrations.RemoveField(
            model_name='update_request',
            name='image_url',
        ),
        migrations.AddField(
            model_name='update_request',
            name='burn_ids',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='update_request',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
