# Generated by Django 5.1.6 on 2025-06-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_alter_update_request_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='update_request',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
