# Generated by Django 5.1.6 on 2025-06-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0009_update_request_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_to_burn', models.IntegerField(default=1000)),
            ],
        ),
    ]
