# Generated by Django 5.1.6 on 2025-07-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0010_appsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethuser',
            name='address',
            field=models.CharField(db_index=True, max_length=42, primary_key=True, serialize=False, unique=True),
        ),
    ]
