# Generated by Django 5.1.6 on 2025-07-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0011_alter_ethuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='base_fee',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
    ]
