# Generated by Django 5.1.6 on 2025-07-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0012_alter_appsettings_base_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lovecraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.BigIntegerField()),
                ('current_owner', models.CharField(max_length=42)),
                ('block_number', models.BigIntegerField()),
                ('timestamp', models.DecimalField(decimal_places=0, max_digits=30)),
                ('transaction_hash', models.CharField(max_length=66)),
            ],
            options={
                'db_table': 'lovecraft',
                'managed': False,
            },
        ),
    ]
