# Generated by Django 5.1.6 on 2025-08-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0013_lovecraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whatcraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.BigIntegerField()),
                ('current_owner', models.CharField(max_length=42)),
                ('block_number', models.BigIntegerField()),
                ('timestamp', models.DecimalField(decimal_places=0, max_digits=30)),
                ('transaction_hash', models.CharField(max_length=66)),
            ],
            options={
                'db_table': 'Whatcraft',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='imageurl',
            name='id',
            field=models.IntegerField(db_index=True, default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
